name: flutter_loading_animation_kit
description: A flutter package which contains a set of beautiful and creative loading animations.
version: 0.0.2
repository: https://github.com/sushmoyr/flutter_loading_animation_kit

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
